services:
  minio: 
    image: 'minio/minio:latest'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniopassword
    ports:
      - '9000:9000'
      - '8900:8900'
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'
volumes:
  minio:
    driver: local
