apiVersion: apps/v1
kind: Deployment
metadata:
  name: mys3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mys3
  template:
    metadata:
      labels:
        app: mys3
    spec:
      containers:
        - name: mys3
          image: ghcr.io/tonymascate/mys3:latest
          ports:
            - containerPort: 8080
          env:
            - name: MINIO_ENDPOINT
              value: "http://minio-service:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "miniopassword"
