apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
    - protocol: TCP
      port: 8900
      targetPort: 8900
  type: ClusterIP
